import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import NavigationHeader from "@/components/NavigationHeader";
import Footer from "@/components/footer";
import { UserProvider } from "@/contexts/UserContext";
import { CartProvider } from "@/contexts/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/Images/home/fav-icon.webp", type: "image/webp" },
      { url: "/favicon.ico", sizes: "any" }
    ],
    apple: { url: "/Images/home/fav-icon.webp", type: "image/webp" },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/webp" href="/Images/home/fav-icon.webp" />
        <link rel="apple-touch-icon" href="/Images/home/fav-icon.webp" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <UserProvider>
            <Header />
            <NavigationHeader />
            {children}
            <Footer />
          </UserProvider>
        </CartProvider>
      </body>
    </html>
  );
}
